### ISSUE TITLE
Node dependencies missing after installation on ubuntu

### ISSUE THREAD

**Issue by iimog** [passB/nodeHostApp#7]
I installed the host app on Ubuntu 16.04.3, node v8.8.1, via the following commands (according to the [documentation](https://passb.github.io/host_application.html)):
```
git clone https://github.com/passB/nodeHostApp.git
cd nodeHostApp
bash install_host_app.sh firefox
```
After this the passB addon still reports an error with the host app.
Direct execution of the host app reveals the problem:
```
$ ~/.mozilla/native-messaging-hosts/passb.sh
module.js:515
    throw err;
    ^

Error: Cannot find module 'chrome-native-messaging'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tank/home/s216121/.mozilla/native-messaging-hosts/index.js:1:85)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
```
In addition to `chrome-native-messaging` the module `cross-spawn` is also missing so the following commands fixed the issue for me:
```
cd ~/.mozilla/native-messaging-hosts
npm install chrome-native-messaging
npm install cross-spawn
```

Is this the best solution or am I missing something? If so, this should be either part of the documentation or of the installation script. I'll gladly send a pull request for whatever you prefer.

**Comment by phryneas** [comment]
could you please test the installation with the current master from https://github.com/phryneas/nodeHostApp and validate that it works now?

also, could you please do a test of the binary installation from https://4-113617828-gh.circle-artifacts.com/0/home/circleci/repo/artifacts/passb_hostapp_22bed214b8be441e36478814270a7a701117bfd9_linux.zip ?
I don't have a linux system at hand for the weekend.

Thanks :)

**Comment by iimog** [comment]
I can confirm that on my system now both methods of installation work :smiley:

<details>
<summary>What I did in detail:</summary>

1. Uninstall current host app with `rm -r ~/.mozilla/native-messaging-hosts/passb*`

2. Check that passB in firefox shows "An error occured communicating with the host application..." after refresh

3. Install via git
```
git clone https://github.com/phryneas/nodeHostApp
cd nodeHostApp
bash install_host_app.sh firefox
```

4. Check that passB in firefox works after restart

5. Repeat 1-4 but replace 3 with: Install via binary
```
cd /tmp
wget https://4-113617828-gh.circle-artifacts.com/0/home/circleci/repo/artifacts/passb_hostapp_22bed214b8be441e36478814270a7a701117bfd9_linux.zip
unzip passb_hostapp_22bed214b8be441e36478814270a7a701117bfd9_linux.zip 
bash install_host_app.sh firefox
```
</details>

**Comment by phryneas** [comment]
thanks a lot!
